### ISSUE TITLE
Mythic Mounts Error (544 dragons)

### ISSUE THREAD

**Issue by AshrielV** [Draylar/crimson-moon#33]
This mod, ahhh, doesn't interact well with mythic mounts. I'm playing with the latest update on 1.18.1- and it spawns hundreds of dragons. No undead- just dragons and slimes. Enough to drop my 200+ fps game to 10.

**Comment by SHXRKIEgg** [comment]
Yeah uhhh, its defs causing a lot of issues xD
![image](https://user-images.githubusercontent.com/79353591/154195641-11cac5e4-3891-4e45-81b4-60536a5eb87a.png)

**Comment by Gamerbolts** [comment]
This is happening to me as well with Mythic Mounts. I just did a butcher command to 1100 dragons. I am not sure if its Crimson Moon or Mythic Mounts but please fix.

**Comment by Draylar** [comment]
This should be fixed in the next update for 1.18.1 and 1.18.2 - please give it a try and let me know if it works. You'll be able to blacklist entities in the `blacklistModid` and `blacklistedEntityID` config option in the config file (by default, mythic mounts & slimes will be blacklisted). Thank you for the report!
