### ISSUE TITLE
Game won't render with shaders

### ISSUE THREAD

**Issue by tired9494** [Draylar/crimson-moon#6]
I know it's not something that's your fault or duty to fix or whatever, but whenever I use shaders with optifine, my game won't render with this mod enabled. If I load into a world with this mod and shaders enabled, my screen is just stuck on the dirt background but I can still hear me moving, mining, etc. If I enable shaders after I load in then it's the same but with the Mojang logo screen instead.

I'm not expecting you to fix it, but if it's something easy to fix then I'd appreciate it.

**Comment by Draylar** [comment]
Yeah, OptiFine compatibility is basically impossible. OptiFabric has been discontinued, so this isn't an issue I plan to address formally, but I would be happy to upload a jar (in the future, after I fix the other wack issues this mod has) that doesn't use Satin or shader effects (no red skies, just extra mob spawns), so that you could still use the mod on older versions. I'll send you an update if I ever get around to it.

**Comment by MrKashew** [comment]
This is going to sound very strange, but it appears that when I have this mod installed w/ optifine and shaders, I cannot render the world. But when I have this mod + immersive portals + optifine w/ shaders, it renders. Is this some sort of coincidence or weird interaction on my end, or is there some sort of unintentional patch going on in there I wonder?

**Comment by Draylar** [comment]
Probably just coincidence, as I couldn't find anything on either repo regarding automatically turning off/disabling when the other mod is present.

**Comment by nekonoire** [comment]
It seems that Optifabric have an update recently. Will there be any chance to have a version without the Satin API so that other shaders can potentially work with this mod? Or maybe instead of having red tint all over, the server can just send out a server wide message that there's a crimson moon while extra mobs are spawning?

**Comment by Draylar** [comment]
1.18.1+ use an internal shader API over Satin, which may or may not support other rendering mods (this is now 100% vanilla shader loading, so anything that doesn't work is _most likely_ out of my control - although I'd be happy to look into compatibility if needed). You can also disable shader usage through the `enableShader` option in the config file.
